"""Regression tests for handoff validation receipt diagnostics wiring."""

from __future__ import annotations

from pathlib import Path
import unittest


class HandoffValidationReceiptCiWiringTests(unittest.TestCase):
    """Ensure the receipt is generated by the reusable CI diagnostics bundle."""

    def test_ci_report_generates_receipt_outputs_after_upstream_artifacts(self) -> None:
        script = Path("scripts/ci_report.sh").read_text(encoding="utf-8")

        evidence_index = script.index("app.cli.evidence_checklist --artifact-dir")
        manifest_index = script.index("app.cli.artifact_manifest --artifact-dir", evidence_index)
        receipt_index = script.index("app.cli.handoff_validation_receipt --artifact-dir")

        self.assertLess(evidence_index, receipt_index)
        self.assertLess(manifest_index, receipt_index)
        self.assertIn("handoff-validation-receipt.md", script)
        self.assertIn("handoff-validation-receipt.json", script)

    def test_ci_report_captures_receipt_help_and_summary(self) -> None:
        script = Path("scripts/ci_report.sh").read_text(encoding="utf-8")

        self.assertIn("handoff-validation-receipt-help.txt", script)
        self.assertIn("handoff validation receipt", script)
        self.assertIn("final receipt", script)


if __name__ == "__main__":
    unittest.main()
